def VAR_1 = "VAR1"
VAR_2 = "VAR2"

public static String STAGE_ONE = "stage one"
public final  String STAGE_TWO = "stage two"

emun Stages {
  STAGE_ONE,
  STAGE_TWO
}

class Stages2 {
  public static String STAGE_ONE = "stage one"
  public final  String STAGE_TWO = "stage two"
}


task()
